---
- hosts: mynodes
  gather_facts: no
  become: true
  tasks:
  - name: Install Python 3
    raw: apk -U add python3
  - name: Install/Update Apache 
    apk:
      name: apache2
      state: latest
  - name: Copy in index.html
    template:
      src: index.html
      dest: /var/www/localhost/htdocs/index.html
    notify:
    - restart apache
  - name: Fire up Apache
    service:
      name: apache2
      state: started
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
